### ISSUE TITLE
Enable failed with administrator permission, command 'extension.enableWindows11VSCode' not found

### ISSUE THREAD

**Issue by VincentAzz** [notAperson535/windows-11-vscode#7]
Enable failed with administrator permission, command 'extension.enableWindows11VSCode' not found 
![图片](https://github.com/notAperson535/windows-11-vscode/assets/95619684/20676c48-74b9-44e2-8d35-0f6ee2040f2e)
![图片](https://github.com/notAperson535/windows-11-vscode/assets/95619684/78846c42-47ce-4998-84c9-e042323bb1b2)

---

Windows-11-vscode Version: v2.0.1 From Marketplace

in

VSCodeVersion: 1.85.1 (user setup)
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows 11 23H2 Windows_NT x64 10.0.22631

and

VSCodeVersion: 1.86.0-insider (system setup)
Date: 2023-12-20T05:36:57.756Z
Electron: 27.1.3
ElectronBuildId: 25612240
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows 11 23H2 Windows_NT x64 10.0.22631

**Comment by notAperson535** [comment]
@VincentAzz Fixed, sorry for the delay
