### ISSUE TITLE
When using dark theme...

### ISSUE THREAD

**Issue by Lukoning** [notAperson535/windows-11-vscode#8]
WHAT THE HELL
![QQ截图20240808133352](https://github.com/user-attachments/assets/40a6290b-3293-45a5-a8e0-a659ba21625d)
![QQ截图20240808134002](https://github.com/user-attachments/assets/d4bfd0f1-f32d-42d9-a518-573ff0b563b1)
![image](https://github.com/user-attachments/assets/e03ddb8e-ebee-4896-8330-c6fc3dac2f1e)

**Comment by Lukoning** [comment]
* I excluded the effects of other plugins that modify workbench.html

**Comment by notAperson535** [comment]
@Lukoning the vscode theme has to match the theme you set for the extension, in this case you should set the extension to the dark theme.
